// seed-job.groovy
// generates job1, job2, job3 in Jenkins via Job DSL plugin
def REPO = "https://github.com/elisacoh/home-assignment-elbit.git"
def BRANCH = "main"

["job1-build-flask", "job2-build-nginx", "job3-integration-test"].eachWithIndex { jobName, i ->
    def path = "jenkins/jobs/job${i + 1}.groovy".toString()

    pipelineJob(jobName) {
        description("Auto-generated by seed job")
        keepDependencies(false)

        definition {
            cpsScm {
                scm {
                    git {
                        remote {
                            url(REPO)
                            credentials("github-creds")
                        }
                        branch(BRANCH)
                    }
                }
                scriptPath(path)
            }
        }

        triggers {
            scm("H/5 * * * *")
        }
    }
}